### ISSUE TITLE
Data.dat inaccesible on linux

### ISSUE THREAD

**Issue by noirscape** [Niels-NTG/FTLAV#1]
After compiling the source, the software prompts me to locate data.dat manually. However by default the steam folder on linux is hidden from view by naming it .steam. (And can't be changed, because that prompts steam to create a new folder.) 
This makes accessing the steam folder impossible and causes users to be unable to run FTLAV.

(I was able to get around it by creating a soft-link to the .steam folder and using that. Here's an example of the command:

```
ln -s ~/.steam ~/steam
```

)

**Comment by Niels-NTG** [comment]
Could give me the exact path that leads to

```
FTL Faster Than Light/data/resources
```

**Comment by Niels-NTG** [comment]
Never mind. I think I've solved it now by changing this

```
~/Steam/SteamApps/common/FTL Faster Than Light/data/resources
```

to this

```
~/.steam/steam/SteamApps/common/FTL Faster Than Light/data/resources
```

I've just committed 8d0a682cbad9c4264ff1f3a1579fe6622648d3ac to fix this. Please let me know if it actually works.

**Comment by noirscape** [comment]
Doesn't work. I'm still prompted to locate data.dat.

```
~/.steam/steam/steamapps/common/FTL Faster Than Light/data/resources
```

is my path to the folder in which data.dat is located. So no caps for the steamapps folder. (Manually changing this didn't fix it either.)

**Comment by Niels-NTG** [comment]
Hmm… just committed 21920b80102615ecbb29d6dd67ec3d2cb5c61a3c that looks for both SteamApps and steamapps.

**Comment by noirscape** [comment]
Commit 88ebbaac8ff204a22a0f1f1482c421cc6913727f fixes the issue. Bug can be closed.
